In the second question, I do calculations for a convolution layer. 

In [ ]:
 # Importing required libraries 
 import numpy as np 
 from scipy.signal import convolve2d
 from skimage.measure import block_reduce as pooling 

# Question 2 

In [ ]:
image = np.array([[2,1,3,3],
                  [1,6,2,5],
                  [1,4,5,2],
                  [6,6,5,3]])
image.shape

(4, 4)

In [ ]:
image_1 = np.pad(image,pad_width = 1)
print(image_1.shape)
print(image_1)

(6, 6)
[[0 0 0 0 0 0]
 [0 2 1 3 3 0]
 [0 1 6 2 5 0]
 [0 1 4 5 2 0]
 [0 6 6 5 3 0]
 [0 0 0 0 0 0]]


In [ ]:
filter1 = np.array([[0,1,2],
                  [1,0,1],
                  [2,1,0]])


filter2 = np.array([[1,0,1],
                  [0,1,0],
                  [1,0,1]])


filter3 = np.array([[1,2,0],
                    [2,0,2],
                    [0,2,1]])


In [ ]:
out_1 = convolve2d(image_1,filter1,mode = 'valid')
out_2 = convolve2d(image_1,filter2,mode = 'valid')
out_3 = convolve2d(image_1,filter3,mode = 'valid')

In [ ]:
print("Convolved image with the first filter is :\n",out_1)
print("Convolved image with the second filter is :\n",out_2)
print("Convolved image with the third filter is :\n",out_3)

Convolved image with the first filter is :
 [[ 2 13 18 12]
 [11 16 33 17]
 [23 34 35 23]
 [15 25 18  7]]
Convolved image with the second filter is :
 [[ 8  4 14  5]
 [ 6 17 12 13]
 [13 18 25  9]
 [10 12 11  8]]
Convolved image with the third filter is :
 [[10 24 17 16]
 [22 23 41 17]
 [28 42 35 28]
 [14 31 32 19]]


In [ ]:
out_pool1 = pooling(out_1, (2,2), np.max)
out_pool2 = pooling(out_2, (2,2), np.max)
out_pool3 = pooling(out_3, (2,2), np.max)

In [ ]:
print("Convolved image with the first filter after max pooling is :\n",out_pool1)
print("Convolved image with the second filter after max pooling is :\n",out_pool2)
print("Convolved image with the third filter after max pooling is :\n",out_pool3)

Convolved image with the first filter after max pooling is :
 [[16 33]
 [34 35]]
Convolved image with the second filter after max pooling is :
 [[17 14]
 [18 25]]
Convolved image with the third filter after max pooling is :
 [[24 41]
 [42 35]]
